Feature/object selector e2e test
EasyDynamics/oscal-editor-deployment pull request #102
Opened 2022-07-05 17:24 UTC by schen2166

Update e2e tests to comply with Drawer Component

Commands:
-Adjusted navToViewer function to comply with the new navigation
where the titleText parameter is removed because now navigating
using the drawer component sections.
-Adjusted the SSP, component, profile, and catalog Viewer
navigations to comply with the parameters used in the navtoViewer
function
- Removed navToTestSspRestMode function entirely
        -1) repeated the functionality found in navToViewer
        -2) the clickable box to labeled "Select Oscal SSP"
            will no longer be needed as it will be suppoted
            with the drawer component friendly URLs

Edit Tests:
-Replaced functions calls for navToTestSspRestMode with
navToSspViewer as an update

Load Tests:
-Replaced function calls for the navToTestSspRestMode with
navToSspViewer function call.
-Removed check for box click as it will be replaced by the drawer
component.

Closes #98

2022-07-06 14:44 UTC, kylelaker commented
Git `user.email` needs to be fixed on this branch as well. Please work with @Bronstrom to correct this.

2022-07-06 16:59 UTC, kylelaker commented
@Bronstrom @schen2166 The commits on this branch need to be amended and force-pushed to ensure they are linked correctly.

2022-07-08 20:21 UTC, schen2166 commented
The tests for this issue on GitHub failed. This may be because the default docker image is still routed to the `Docker image` without the drawer component. I've tested my cypress tests locally and they have all passed. 

**Note: The Catalog Tests occasionally fail** but that is because the Catalog is a large file and can take time to load. Currently, the test will wait 1 second for the Catalog to load (controlled by line 31 of `commands.js`). This can be resolved by increasing the cypress wait time or by rerunning the test.

The tests in Load and Edit don't pass because I've restructured the functions defined in `command.js` to accommodate the features implemented in the drawer. They pass in local testing as well.
<img src="https://user-images.githubusercontent.com/106985986/178063365-458e6ddc-914e-49b2-b474-132d9af9db34.png" width="600">
<img src="https://user-images.githubusercontent.com/106985986/178063923-63de8632-2ef6-4ee9-a623-18629b6a93b1.png" width = "300"><img src ="https://user-images.githubusercontent.com/106985986/178064805-442308c6-aab6-4ff8-b2bf-d92970b93bb0.png" width = "380">

2022-07-11 12:32 UTC, kylelaker requested changes

2022-07-11 12:32 UTC, kylelaker commented on end-to-end-tests/cypress/e2e/OSCAL/Drawer.cy.js
> +    cy.contains("SSP");
```suggestion
    cy.contains("System Security Plan");
```

2022-07-11 12:50 UTC, kylelaker commented on end-to-end-tests/cypress/e2e/OSCAL/OSCAL_Load_Tests.cy.js
>      cy.contains('OSCAL SSP URL').first().should('exist').next().click().clear().type(Cypress.env('base_url') + "/oscal/v1/system-security-plans/cff8385f-108e-40a5-8f7a-82f3dc0eaba8")
```suggestion
    cy.contains('OSCAL System Security Plan UR:').first().should('exist').next().click().clear().type(Cypress.env('base_url') + "/oscal/v1/system-security-plans/cff8385f-108e-40a5-8f7a-82f3dc0eaba8")
```

2022-07-11 14:12 UTC, schen2166 commented
I looked into configuring the `defaultTimeout` and I'm wondering if that is really the best option to go with. Cypress's default timeout is 4000ms and if we increase that in the configuration file then that will increase the timeout for all commands regardless. 

The other approach to this is to change the timeout at a command level so that it will wait longer for that specific command for a longer time and leave the default time for the other commands to be 4000ms.

This is what I've been considering:
*Configuring Globally*:
If more files to be added in the future, then there might be additional wait time for the commands that don't take as much time to load and could potentially increase testing time where the tests are doing nothing. And the wait time is increased for this one component to load.
*Configuring at Command level*:
Makes the test run more efficient by allocating the exact time required for the commands that take longer to load but will be harder to maintain if there are multiple large files. Fortunately, defining your own macros in the config file can help with the maintenance by applying that macro only to those commands.

Which approach do you think is the best option?

2022-07-11 14:15 UTC, tuckerzp commented
> Configuring at Command level

I think this is the best option.

2022-07-11 18:51 UTC, tuckerzp commented on end-to-end-tests/cypress/support/commands.js
> +  cy.contains(viewerLinkText).children('#class="MuiTreeItem-iconContainer"').click();
Like here I feel like looking for a specific class of children is not really how a user would use the `Editor`. Why not just wait until the `Catalog` button is clickable, click it, then check for a specific file?

2022-07-11 19:27 UTC, kylelaker requested changes

2022-07-11 19:27 UTC, kylelaker commented on end-to-end-tests/cypress/e2e/OSCAL/Drawer.cy.js
> +System Security Plan Editor */
```suggestion
```

2022-07-12 12:18 UTC, kylelaker requested changes

2022-07-12 12:18 UTC, kylelaker commented on .github/workflows/container-test-deploy.yml
> +            OSCAL_REST_SERVICE_GIT_BRANCH=feature/combined-test
This must be reverted (and the related PRs must be merged) before this can be merged.

2022-07-12 13:51 UTC, kylelaker approved these changes

2022-07-12 14:08 UTC, merged